
CREATE DATABASE test;

USE test;

DROP TABLE IF EXISTS push_message;

CREATE TABLE IF NOT EXISTS push_message (
	ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CONTENT VARCHAR(255),
	STATUS VARCHAR(10),
	CREATED_BY VARCHAR(50),
	CREATED_AT TIMESTAMP,
	LAST_MODIFIED_AT TIMESTAMP
);